FROM node:20-alpine as build
WORKDIR /app
COPY . .

RUN npm ci
RUN npm run build --prod

RUN echo "--- DIST CONTENT ---" && ls -la /app/dist/bookstore-crm/browser

FROM nginx:alpine
RUN mkdir /usr/share/nginx/bookstore-crm
COPY --from=build /dist/bookstore-crm/browser /usr/share/nginx/bookstore-crm
COPY bookstore-crm.conf /etc/nginx/conf.d/default.conf
